version: '2'
services:
  par:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
       - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=ecotex-server
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
volumes:
   db_data:
